name: ubuntu

on: [push]

jobs:
  test-linux:
    name: Test on PlantUML Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install PlantUML
        run: |
          curl -L https://github.com/riboseinc/plantuml-install/raw/master/ubuntu.sh | sudo bash
      - name: Make
        run: |
          make all
