name: windows

on: [push]

jobs:
  test-windows:
    name: Test on Ruby ${{ matrix.ruby }} Windows
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ '2.6', '2.5', '2.4' ]
    steps:
      - uses: actions/checkout@master
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'
      - name: Update gems
        shell: pwsh
        run: |
          $docTypes = ConvertFrom-StringData (Get-Content ./doctypes.env -Raw)
          gem install metanorma-cli metanorma-$($docTypes.TYPE)
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '8'
      - name: Install Puppeteer
        shell: pwsh
        run: |
          npm install -g puppeteer
      - name: Metanorma compile
        shell: pwsh
        run: |
          $docTypes = ConvertFrom-StringData (Get-Content ./doctypes.env -Raw)
          $docTypes.DOCTYPES.Split(" ") | ForEach {
            $t = $_.Trim('"')
            metanorma new result\$t --type $($docTypes.TYPE) --doctype $t --template . --overwrite
            if (Test-Path -Path result\$t\document.adoc) {
              metanorma compile result\$t\document.adoc
            } else {
              Get-ChildItem ".\result\$t" -Filter *.adoc | Foreach-Object {
                metanorma compile $_.FullName
              }
            }
          }